Locations admin view
DAT-ETSIT/taquillas pull request #71
Opened 2020-08-16 07:01 UTC by epelaez1

This PR contains a rebase of the PRs #69 and #70

2020-10-24 16:19 UTC, YagoGG commented
¡Hola, @epelaez1! Muchas gracias por el PR.

He estado haciendo pruebas funcionales, y he encontrado los siguientes 2 problemas:

1. La barra de búsqueda en el panel de administración (vista de Localizaciones) aparece como un "doble elemento": es una caja de texto + la línea de texto habitual de Material Design:
    ![image](https://user-images.githubusercontent.com/7356565/97086685-2d078280-1625-11eb-815e-a0086ff49c1c.png)
2. En la misma vista, al darle al botón "+", seleccionar cualquiera de los campos de la nueva fila, y pulsar una tecla, hay un error en el frontend y desaparece toda la página web.

Por favor, échales un vistazo cuando puedas y avísame si puedes reproducirlo. Asimismo, si pudiésemos cambiar "Localizaciones" por "Ubicaciones", creo que sería una traducción más fidedigna.

Por cierto, he actualizado tu rama ahora que ya hemos mergeado #69 y #70 para que no tenga conflictos.

¡Gracias de nuevo!

2020-10-24 16:20 UTC, YagoGG requested changes
¡Hola, @epelaez1! Muchas gracias por el PR.

He estado haciendo pruebas funcionales, y he encontrado los siguientes 2 problemas:

1. La barra de búsqueda en el panel de administración (vista de Localizaciones) aparece como un "doble elemento": es una caja de texto + la línea de texto habitual de Material Design:
    ![image](https://user-images.githubusercontent.com/7356565/97086685-2d078280-1625-11eb-815e-a0086ff49c1c.png)
2. En la misma vista, al darle al botón "+", seleccionar cualquiera de los campos de la nueva fila, y pulsar una tecla, hay un error en el frontend y desaparece toda la página web.

Por favor, échales un vistazo cuando puedas y avísame si puedes reproducirlo. Asimismo, si pudiésemos cambiar "Localizaciones" por "Ubicaciones", creo que sería una traducción más fidedigna.

Por cierto, he actualizado tu rama ahora que ya hemos mergeado #69 y #70 para que no tenga conflictos.

¡Gracias de nuevo!

2020-10-24 16:22 UTC, YagoGG commented
Por cierto, ambos problemas me aparecen también en #72. Imagino que es por la configuración global del componente de la tabla; te aviso porque supongo será necesario actualizar todos los PRs.

2021-04-10 12:26 UTC, epelaez1 commented
Buenas @YagoGG!

Los errores se debían a alguna actualización que metieron a material-table. Cada vez que actualizan se suelen cargar algo así que he fijado la versión a una en concreto. La línea de la caja de búsqueda tampoco me aparecía antes, pero no he sabido encontrar la versión que teníamos donde funcionaba bien así que he hecho un apaño por css. 

He cambiado lo de Localizaciones por Ubicaciones.
Y al actualizar los paquetes han aparecido errores del linter  que antes no estaban, los he arreglado también. 

Con la versión que he fijado el resto de PR deberían funcionar correctamente  también.

2021-04-10 14:54 UTC, merged

2021-04-10 14:54 UTC, YagoGG approved these changes